### ISSUE TITLE
Task 2

### ISSUE THREAD

**Issue by Huskova** [dimakruhlyi/FE#1]
https://github.com/dimakruhlyi/FE/blob/7705d9bd716a4b64612d1d0c95607dcb46be3171/html%2Bcss/Task_2(26.10.2019)/index.html#L128

Пробел можно заменить https://www.w3schools.com/html/html_entities.asp

Не могу вставить символ, заменяется на пробел ))

**Comment by dmytrokruhlyi** [comment]
исправлено)
